sudo: false
language: c
cache:
  directories:
  - $HOME/.ghc
  - $HOME/.cabal
  - $HOME/.stack

matrix:
  include:
  # grab the appropriate GHC and cabal-install versions from hvr's PPA.
  - env: BUILD=cabal GHCVER=7.8.4 CABALVER=1.22
    compiler: ": #GHC 7.8.4"
    addons:
      apt:
        packages:
          - cabal-install-1.22
          - ghc-7.8.4
        sources: [hvr-ghc]

  - env: BUILD=cabal GHCVER=7.10.3 CABALVER=1.22
    compiler: ": #GHC 7.10.3"
    addons:
      apt:
        packages:
          - cabal-install-1.22
          - ghc-7.10.3
        sources: [hvr-ghc]

  - env: BUILD=cabal GHCVER=8.0.1 CABALVER=1.24
    compiler: ": #GHC 8.0.1"
    addons:
      apt:
        packages:
          - cabal-install-1.24
          - ghc-8.0.1
        sources: [hvr-ghc]

  # The Stack builds. We can pass in arbitrary Stack arguments via the ARGS
  # variable, such as using --stack-yaml to point to a different file.
  - env: BUILD=stack ARGS="--resolver lts-7"
    compiler: ": #stack 8.0.1"
    addons:
      apt:
        packages:
          - ghc-8.0.1
        sources: [hvr-ghc]

before_install:
# Using compiler above sets CC to an invalid value, so unset it
- unset CC

# Download and unpack the stack executable
- export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$HOME/.local/bin:$PATH
- mkdir -p ~/.local/bin
- curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
- echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
- if [ -f configure.ac ]; then autoreconf -i; fi
- |
  case "$BUILD" in
    stack)
      stack --no-terminal --install-ghc $ARGS test --flag 'aeson:fast' --only-dependencies --fast
      ;;
    cabal)
      cabal --version
      travis_retry cabal update
      cabal install --only-dependencies --enable-tests --enable-benchmarks --force-reinstalls --ghc-options=-O0 --reorder-goals --max-backjumps=-1 $CABALARGS
      ;;
  esac

script:
- |
  case "$BUILD" in
    stack)
    stack --no-terminal test --haddock --no-haddock-deps --ghc-options="-Wall -fno-warn-unused-do-bind -Werror"
      ;;
    cabal)
      cabal configure --enable-tests -v2 --ghc-options="-O0 -Werror"
      cabal build
      cabal check
      cabal test
      cabal copy
      cabal sdist
      SRC_TGZ=$(cabal info . | awk '{print $2;exit}').tar.gz && \
        (cd dist && cabal install --enable-tests --force-reinstalls "$SRC_TGZ")
      ;;
  esac
